### ISSUE TITLE
Error when adding contributors to a dataset

### ISSUE THREAD

**Issue by essvee** [NaturalHistoryMuseum/ckanext-attribution#24]
**Description**
Attempting to add a contributor to a dataset's metadata causes an error (screenshot 1 below). The error occurs even if the portal user account has been added to the dataset as an 'editor' or 'admin' or if the account used is the same one used to create the dataset. 
 
**To Reproduce**
Log in using a non-admin account, try and add a contributor to a new or existing dataset (screenshot 2). It looks like it's worked (screenshot 3) until you hit 'update dataset' and then you get the 403 error message shown in the screengrab. The example is from this dataset: https://data.nhm.ac.uk/dataset/bound-volumes-and-exsiccatae, but seems to be happening across all the datasets on live. 

**Screenshots**

1 - ![image](https://user-images.githubusercontent.com/12844459/189676903-34657129-0ff1-4457-ab3e-ff8f495ef91b.png)
2 - ![image](https://user-images.githubusercontent.com/12844459/189678115-89322311-797d-4239-8654-be9d5fe75e54.png)
3 - ![image](https://user-images.githubusercontent.com/12844459/189678168-1bbe931c-091c-4965-a816-9238d3450282.png)

**Comment by alycejenni** [comment]
This is because it's trying to change an existing contributor (I don't know why yet), which only sysadmins are allowed to do.
